# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags/
  # Categories: /categories/
  About: /about/

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

# LaTeX support (via MathJax)
latex: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: jing-sam@qq.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/jingsam
  weibo: http://weibo.com/u/1902650267
  zhihu: https://www.zhihu.com/people/jingsam
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname: 

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
# Demo: https://gitalk.github.io
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  github_id: GitHub repo owner
  repo: GitHub repo
  client_id: GitHub Application Client ID
  client_secret: GitHub Application Client Secret
  admin_user: GitHub repo owner and collaborators, only these guys can initialize github issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language:

# utterances
utterances:
  enable: true
  repo: jingsam/jingsam.github.io
  issueTerm: title
  theme: github-light
  label: utterances

# ===========================================
# Version
# ===========================================
version: 2.11.0
