# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  # About: /about

# site search option
search: false

# Fancybox
fancybox: true

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default

# ===========================================
# Social links Settings
# ===========================================
social:
  email: your@email.com
  stack-overflow:
  twitter:
  facebook:
  github: 
  weibo: 
  zhihu: 

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 
# Google Analytics
google_analytics: 

# Duoshuo
duoshuo_shortname: 
# Disqus
disqus_shortname: 


# ===========================================
# Version
# ===========================================
version: 2.0.0