# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /images/favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  # Github: https://github.com/ahonn
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: false
  fancybox: false

copyright:
  enable: false
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: ahonn95@outlook.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/ahonn
  weibo:
  zhihu: https://www.zhihu.com/people/ahonn/activities
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 0a275bcf7d954b807e1db498d8e5b192
# Baidu Verification
baidu_verification: 0a275bcf7d954b807e1db498d8e5b192

# Google Analytics
google_analytics: UA-74273646-1
# Google Verification
google_verification: j5dWC85DkoAfUR50W00ewfii3X9ouH55HnyBP6oZxGE

# Disqus
disqus_shortname: ahonn

#Changyan
changyan:
  appid:
  appkey:

# ===========================================
# Version
# ===========================================
version: 2.5.0
